### ISSUE TITLE
Test run doesnt start from workspace (overrrides config.json)

### ISSUE THREAD

**Issue by VadymPatuk** [jimmymcp/al-test-runner#102]
Hi James,

Has same issue https://github.com/jimmymcp/al-test-runner/issues/98

Figured out that using workspaces with this definition your extensión works well (same if only `app.Test` openned in VS)

```
{
  "folders": [
    {
      "path": "app"
    },
    {
      "path": "app.Test"
    },
    {
      "path": ".AL-Go"
    }
  ],
  "settings": {}
}
```

But if you change with this one extension stop working. After run test its loading indefinitely and never ends.
```
{
    "folders":  [
                    {
                        "path":  ".AL-Go"
                    },
                    {
                        "path":  "app"
                    },
                    {
                        "path":  "app.Test"
                    }
                ],
    "settings":  {
                    
                 }
}
```

Did you try format workspace file @alexandr-gladkiy @vengo2021 ?

**Comment by VadymPatuk** [comment]
@vengo2021 ok same here, excluding `.AL-Go` folder from workspace fixes issue.

Worth mention that both app was added with `Actions` from AL-GO Pte template https://github.com/microsoft/AL-Go-PTE (example https://github.com/VadymPatuk/example-al-test-runner/actions)

Maybe workflow action somehow rearrange data in workspace file and make it incompatible with AL-Test-Runner :confused:

![image](https://github.com/jimmymcp/al-test-runner/assets/107999046/0374a8c2-615f-40d5-b0c7-56d912a5f3f7)

**Comment by jimmymcp** [comment]
Thanks for the repo to reproduce the problem, very helpful. It's a combination of
- the launch configuration for each app is in the .vscode folder per app (as opposed to in the workspace or user settings - which I always use now so couldn't see the problem at first)
- the first folder in the workspace does not contain the launch settings (because the first folder was the .AL-GO folder)

Fix coming, I'll push into the pre-release first and then into the release later on.
