### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by FrankAuwers** [jimmymcp/al-test-runner#115]
If you use namespaces in your test codeunits. The test runner will not detect the test function in these codeunits.

**Comment by B-Wissler** [comment]
Hi @jimmymcp, @FrankAuwers,

the problem is, that the first lines (sometimes 20 lines) contain using commands to include different namespaces
![image](https://github.com/jimmymcp/al-test-runner/assets/144147558/3e7e18a3-d5dc-447f-92fc-1d8e2e951915)
... and this plugin only searches for "Subtype = Test" in the first 10 lines

**Comment by jimmymcp** [comment]
hi @FrankAuwers and @B-Wissler, a new version of the pre-release is going through now (10.10.6). Please let me know if that fixes the issue and I will update the release version as well. (Just changed it to look at the first 50 lines of the codeunit to determine if it is a test codeunit)

**Comment by B-Wissler** [comment]
Yep, that fixes the problem. Thx for your quick response.
