### ISSUE TITLE
bccontainerhelper not navcontainerhelper

### ISSUE THREAD

**Issue by aptMattKoe** [jimmymcp/al-test-runner#25]
I got these error message (sorry, in german) while I want to start the tests or one test:
![image](https://user-images.githubusercontent.com/57363453/95093869-87e64200-0729-11eb-9150-7eb7dd2d4b5b.png)
It says that there is no module like navcontainerhelper. And thats correct because I have installed bccontainerhelper.
Is that currently a problem? :)

**Comment by jimmymcp** [comment]
Hi,

AL Test Runner (since v0.4.1) will test for the existence of bccontainerhelper and load that if it does. If not, it will load navcontainerhelper. Has bccontainerhelper been installed with Install-Module?

If you run the following in a PowerShell prompt what does it show? This is how it is checking for the existence of the module.

Get-Module -ListAvailable | Where-Object Name -eq 'bccontainerhelper'

**Comment by aptMattKoe** [comment]
mmhh I my assumption of the error was not correct. On this server was no bccontainerhelper installed (i was realy sure it is) and you are right.
I think I've done something wrong. Thanks for your fast reply! :)
