### ISSUE TITLE
Run Tests creates new AL file?

### ISSUE THREAD

**Issue by fvet** [jimmymcp/al-test-runner#58]
Trying to get started with the AL Test Runner on a new machine, and I always get a new .al file when trying to Run Tests?
Any clue what could be interfering? (other VS Code extension, missing setting, ...)

![NewFile](https://user-images.githubusercontent.com/25268332/155140070-59ac2c7b-821a-4c01-b67f-0d3d832b0a6b.gif)

**Comment by jimmymcp** [comment]
Is the file saved? I think I had something similar earlier that the AL extension wouldn't compile the app until there were no unsaved changes in the file. I had a situation where it was prompting me to overwrite or merge the changes and wouldn't publish until I'd done that.

I'm pretty certain it will be something to do with the AL Language extension publishing rather than AL Test Runner. You could change the "publish before test" option to confirm.

**Comment by pzentner** [comment]
I also have the same issue. It only happens when you select run tests (either one or all), but doesn't happen when you publish the app without running tests.

**Comment by fvet** [comment]
@jimmymcp The file is saved.

Right now, the publish before test is set to 'None'.
I now always publish manually (via AL: Publish ...), before running the tests.

PS: Running the insider vsix of the AL Language extension

![image](https://user-images.githubusercontent.com/25268332/155537497-9c3f6085-8437-44c8-83f0-8fde46af5b03.png)

**Comment by jimmymcp** [comment]
What is your workspace set up? Do you have the tests in a separate app in a multi-root workspace? Or are the tests in the same app as the rest of the source code? Do you have the "Test Folder Name" setting (in VS Code settings for AL Test Runner) set? If not, please try setting that to the name of the workspace folder that contains the tests and let me know if that makes a difference. Thanks.
