### ISSUE TITLE
Unpublish after test

### ISSUE THREAD

**Issue by lksg** [jimmymcp/al-test-runner#9]
Hi,

I'd love to have the option to unpublish the Test-App after my test run. In BC14 I'm sadly forced to unpublish via powershell after executing my tests. This would enhance my workflow quite a bit during TDD. Usually I'd write a PR but I have too many tasks as is. Thanks for considering it.

Cheers Leon

**Comment by jimmymcp** [comment]
Hi Leon,

I'm wondering about adding some new settings so that you could execute some arbitrary PowerShell before and after the tests have run. If I included some placeholders for common values e.g. {0} = container name, {1} = container credential, {2} = app name, {3} = extension id etc.

I think that would address the problem? You could execute Unpublish-NavContainerApp after the tests have run. Sound reasonable?

**Comment by jimmymcp** [comment]
Included in v0.2.5

You could set the new postTestCommand setting to:

Unpublish-NavContainerApp (Get-ContainerName) -appName (Get-ValueFromAppJson -KeyName name) -uninstall

to uninstall the current app from a local container. Or

Invoke-CommandOnDockerHost {param($a, $b) Unpublish-NavContainerApp $a -appName $b -uninstall} -Parameters (Get-ContainerName), (Get-ValueFromAppJson -KeyName name)

to run the same command on the Docker host. More details at https://jpearson.blog/al-test-runner-for-visual-studio-code/
